### ISSUE TITLE
Could this be used with firebase functions?

### ISSUE THREAD

**Issue by johhansantana** [faastjs/faast.js#32]
Wondering if this would be possible using this library?

**Comment by acchou** [comment]
Firebase functions isn't supported by faast.js right now. From what I can tell, there is a separate API so adding it would require adding another provider implementation. Google's documentation seems to indicate that firebase functions might not be a good fit for batch workloads, but I haven't tried testing it. Are there APIs that firebase provides that you're interested in calling?
