### ISSUE TITLE
custom provider?

### ISSUE THREAD

**Issue by jasonswearingen** [faastjs/faast.js#33]
Hi, I run a SaaS (PhantomJsCloud.com) and I'm going to be updating my site+docs "soon (TM)".   

 As everything I have done is in Typescript, and all my API calls are stateless, it seems that integrating with faast.js might be a good idea.

So, how to get started?    I'd like to know if there are already plans in the works to support custom/3rd party providers, and if so, what those plans are.   

Conversely:  If there are currently no plans and supporting 3rd parties is a non-priority, I'd like to know that too.

Thank you much.

**Comment by acchou** [comment]
Opening up to third party providers is something on the horizon, but there are no specific plans at the moment. In general it would make the most sense to add providers that can support large batch workloads of 100-1000+ cores per user, with lots of spikiness.

That said, faast.js is designed for plugging in new prodivers. The existing AWS, google, and local implementations (in their respective directories) are already well separated. The file `src/provider.ts` has the interface between the faast.js runtime and provider implementations. If you'd like to attempt it I would welcome a PR, which may be in a separate branch for now.

**Comment by jasonswearingen** [comment]
OK thanks, I'll take a look at integrating after my next pass of my website docs.

FYI when you get to the point of 3rd party integrations you might consider building an autoscaler as part of your platform.   In my circumstance I find a pretty good bang-for-the-buck by having the client autoscaler ramp up (maybe start with 8, +1 parallel every 3 seconds)  and if the client is returned a HTTP 429 (throttled) error to delay autoscale growth for a while (say, 45 seconds) and then start growing again.    The benefit of this is only requiring the service to send a single "throttle" signal in the form of 429 errors, and have the client figure the rest out for itself.
