### ISSUE TITLE
Improve `addDirectory`

### ISSUE THREAD

**Issue by teppeis** [faastjs/faast.js#57]
Currently `addDirectory: "aaa"` copies the sub directory of `aaa` under working directory in Lambda.

Project structure:
```
project-root
└── aaa
    └── bbb
        └── ccc
            └── file.js
```
Result:
```
working-dir-in-lambda
├── bbb
│   └── ccc
│       └── file.js
└── index.js
```
Is this intensional?

My expected behavior is coping `aaa` itself and the directory structure is preserved:

```
working-dir-in-lambda
├── aaa
│   └── bbb
│       └── ccc
│           └── file.js
└── index.js
```

The cause is the second arg `false` of `archive.directory()`.
https://github.com/faastjs/faast.js/blob/2b22487a1c4466b0b5843cf8a897bb19f7a477f3/src/packer.ts#L94
If the second arg is omitted, it works as expected.
```js
 archive.directory(await resolvePath(dir), false); 
```

ref. https://www.archiverjs.com/archiver#directory

**Comment by acchou** [comment]
This was a deliberate choice when designing the `addDirectory` feature, though only because I had the thought that there might be applications where putting the contents of the directory in the working directory of the lambda function might be important. But I didn't have any concrete examples in mind. Since it's not difficult to resolve this by adding another subdirectory, do you feel that the behavior of `addDirectory` is worth changing, or perhaps documented better?

**Comment by acchou** [comment]
After using `addDirectory` a bit, I think you are right that it's confusing with these semantics, and should be changed.

**Comment by teppeis** [comment]
Great!

My another request is adding `addGlob`.
For example, I want to include only specific file type:
```js
addGlob: ['src/**/*.js']
```
In addition, I want to exclude certain files or directories.
```js
addGlob: [{pattern: 'src/**/*.js', options: {ignore: '**/*_test.js'} }]
```
https://www.archiverjs.com/archiver#glob helps this implementation.

Currently, users can sort out any file by creating a zip and then `addZipFile`, but it's redundant.

Should I create another issue?

**Comment by acchou** [comment]
Yes let's create another issue and discuss there. I'd like to understand the use case some more.

**Comment by teppeis** [comment]
I'm trying to build JavaScript files with faast.js.

My large project has 100 entry points and it takes about 1 minute to build per each entry point. Even if I execute 4 jobs concurrently with 4 core MacBook, it takes 25 minutes total.

As a result of the experiment with faast.js, it could be done within 2 minutes including overhead! Because the maximum concurrency of Lambda is 1,000.

So I would like to introduce faast.js into the existing project without changing the directory structure and the build settings as much as possible. Also, because there are a lot of files that are unnecessary for building JavaScript, I want to exclude them to reduce the size of the Lambda environment to transfer.

`addDirectory` with preserving directory structure and `addGlob` are the solution I want.

**Comment by acchou** [comment]
Interesting, what build system and framework are you using? Is it essentially running tsc and webpack once for each entry point?

Lambda has a default concurrency limit of 1000, but you can request more. I was able to ask for 5k without much of a fuss. Though with only 100 entry points the default probably wouldn't be a real limitation.

**Comment by teppeis** [comment]
> Interesting, what build system and framework are you using? Is it essentially running tsc and webpack once for each entry point?

Closure Compiler. Yes, it's running Closure Compiler for type checking (like tsc) and bundling (like webpack) once for each entry point.
It's over 400K LOC JS project. :scream:

My build tool is this. I'm trying to add faast.js into this.
https://github.com/teppeis/duck

**Comment by acchou** [comment]
Got it. I'm working through the design of this feature and one thought occurs to me: does it matter what order `addDirectory`, `addZipFile`, and `addGlob` operate w.r.t. each other? I can see cases where you might want to have an ordering to ensure later additions overwrite earlier additions. This could be accomplished by mashing these options into a single `addEntry` option that takes an array of `Entry`, where each entry specifies a zip, directory, glob, or exclude.

This makes the interface semantics consistent but harder to use, and more webpack-like in its nested complexity.

**Comment by acchou** [comment]
Note that I've already added the beginnings of this idea to the `inception` branch, e.g. the `AddDirectoryOption`:

https://github.com/faastjs/faast.js/blob/inception/src/provider.ts#L23

This was needed to allow the user to specify which directory an input directory should be placed into on the remote side.

**Comment by acchou** [comment]
Try `include` / `exclude` in v3 and let me know if it works for your use case.

**Comment by teppeis** [comment]
@acchou Awesome! The options and implementation are simplified and extensible.
It works well in my project.
Thanks!
